name: Build on push

on:
  push:
    branches:
      - master
      - next

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-yocto.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [build]
    secrets: inherit
    with:
      build_id: ${{ github.run_id }}
  publish-test-results:
    uses: ./.github/workflows/publish-results.yml
    needs: test
    secrets: inherit
    with:
      workflow_id: ${{ github.run_id }}
      event_name: ${{ github.event_name }}
      event_file: ${{ github.event_path }}
      commit: ${{ github.sha }}
